### ISSUE TITLE
Exercise 047 - Need explanation for for loop syntax `*alien`?

### ISSUE THREAD

**Issue by nahuakang** [ratfactor/ziglings#111]
In exercise 047, we have [this line](https://github.com/ratfactor/ziglings/blob/63f25f7a73c7405087a1e6ac518c7caa58ac2826/exercises/047_methods.zig#L83-L87):
```zig
        // Loop through every alien...
        for (aliens) |*alien| {

            // *** Zap the Alien Here! ***
            ???.zap(heat_ray_strength);
```

And I don't know what `*alien` represents. I tried using `alien` and the compiler complains that `error: expected type '*Alien', found '*const Alien'`. I tried using `&alien` and the compiler complains that `error: expected 'an identifier', found '&'`.

But in Ziglings we haven't covered this syntax? Why wouldn't `alien` or `&alien` (like Rust's pattern match) work? Thanks :)

**Comment by nahuakang** [comment]
According to [the official reference](https://ziglang.org/documentation/master/#for), this `for (items) |*item|` syntax is to `[i]terate over the slice by reference by specifying that the capture value is a pointer`. Maybe we could add this to the exercise?

**Comment by ratfactor** [comment]
I like your addition. I'll go ahead and close this issue since #112 will solve it. Feel free to re-open if needed. Thanks!
