### ISSUE TITLE
HEY EVERYBODY!

### ISSUE THREAD

**Issue by ratfactor** [ratfactor/ziglings#113]
This seems like a better place than the README to let everyone know I'm still alive and well and very much interested in the future of Ziglings. I see the PRs and issues as they come in. I've also had some excellent feedback via email. I know better than to promise any sort of timeline, but I'm ready to dive into this Real Soon. Thank you all for the activity and your patience!

**Comment by alexgenaud** [comment]
Thanks for your excellent work. I'd barely be able to compile "Hello World" without ziglings. :)

**Comment by ratfactor** [comment]
Gonna go ahead and close this now that I'm actually making some visible progress through the issues. :smile:
