### ISSUE TITLE
Cannot build with Zig 0.9.1

### ISSUE THREAD

**Issue by ldwrs** [ratfactor/ziglings#114]
"Error: Sorry it looks like your version of zig is too old" - while i'm on the latest version...

**Comment by ratfactor** [comment]
@ldwrs You are correct that 0.9.1 is the latest release.  For better or worse, Zig development (before v1.0) is moving quickly and has "breaking changes" all the time. For that reason, it's recommended that you always use the latest snapshot from master when learning or experimenting with Zig:

https://ziglang.org/download/

By contrast, targeting a specific release would make sense for a large project.

Please also see "A Note About Versions" in the Ziglings README here:

https://github.com/ratfactor/ziglings#a-note-about-versions

I took a look and Ziglings does explain this in the error message you mention. Do you think this could be worded better (or more thoroughly?)

```
            \\ERROR: Sorry, it looks like your version of zig is too old. :-(       
            \\
            \\Ziglings requires development build
            \\
            \\    {}
            \\
            \\or higher. Please download a development ("master") build from
            \\
            \\    https://ziglang.org/download/
            \\
            \\
```

**Comment by ldwrs** [comment]
Ah, you're right, it is explained in this error message. I didn't read it carefully and figured it required 0.01 instead of 0.1. My mistake.

**Comment by ratfactor** [comment]
@ldwrs Awesome, thanks for checking!
