### ISSUE TITLE
Comptime inline while loop failed to compile

### ISSUE THREAD

**Issue by liu-minghua** [ratfactor/ziglings#117]
.\exercises\072_comptime7.zig:43:54: error: operation caused overflow
        comptime var digit: u8 = instructions[i + 1] - '0';

**Comment by ratfactor** [comment]
@liu-minghua I'm pretty sure this is because your attempted solution is not correct. If you want, you can peek at the compiler-accepted answer in `patches/patches/072_comptime7.patch`.

**Comment by liu-minghua** [comment]
Thanks so much.

**Comment by ratfactor** [comment]
Closing as solved. Feel free to re-open. :smile:
