### ISSUE TITLE
Ex. 10 unexpectedly fails due to missing type

### ISSUE THREAD

**Issue by rsyring** [ratfactor/ziglings#12]
Ex. 10 is focused on `if` expressions.  The line we are supposed to be fixing is:

https://github.com/ratfactor/ziglings/blob/f33d6983028e550ea22cc5b84b1d85efeed37ec9/exercises/10_if2.zig#L13

My first attempt at fixing this was:

```zig
var price = if (discount) 17 else 20;
```
which resulted in error:

```
./exercises/10_if2.zig:13:31: error: cannot store runtime value in type 'comptime_int'
    var price = if (discount) 17 else 20;
                              ^
```
It took me awhile to figure out that I needed to add the type:

```zig
var price: u8 = if (discount) 17 else 20;
```

I'm not sure if that additional challenge was intended.  The example in that file gave a good hint that type would be needed, but up to this point in the exercises, the "challenge" was always explicit.  The missing type deceleration for price was an implicit challenge and broke the pattern I was expecting up to this point.  

IMO, remove the implicit nature of the challenge by adding the type to the line, adding a hint in the comments that some extra troubleshooting will be involved, or another "???" where the type should go. 

Thanks.

**Comment by ratfactor** [comment]
Agreed on all counts.  It made a _little_ more sense before I removed a (misleading) explanatory comment due to issue #1.

I'll add the type to the exercise. Thank you very much for pointing this out!
