### ISSUE TITLE
Ex 50 requires '!s' in std.debug.print

### ISSUE THREAD

**Issue by timos-komni** [ratfactor/ziglings#121]
_Compiling 050_no_value.zig...
/snap/zig/5567/lib/std/fmt.zig:508:17: error: cannot format error union without a specifier (i.e. {!} or {any})
                @compileError("cannot format error union without a specifier (i.e. {!} or {any})");
                ^
/snap/zig/5567/lib/std/fmt.zig:183:23: note: called from here
        try formatType(
                      ^
/snap/zig/5567/lib/std/io/writer.zig:28:34: note: called from here
            return std.fmt.format(self, format, args);
                                 ^
/snap/zig/5567/lib/std/debug.zig:93:27: note: called from here
    nosuspend stderr.print(fmt, args) catch return;
                          ^
./exercises/050_no_value.zig:74:20: note: called from here
    std.debug.print("{s} {Err!s} / ", .{ first_line1, first_line2 });
                   ^
./exercises/050_no_value.zig:67:20: note: called from here
pub fn main() void {
                   ^
050_no_value.zig: The following command exited with error code 1:
/snap/zig/5567/zig build-exe /home/timos/Projects/zg/ziglings/exercises/050_no_value.zig --cache-dir /home/timos/Projects/zg/ziglings/zig-cache --enable-cache 

Edit exercises/050_no_value.zig and run this again.
To continue from this zigling, use this command:
    zig build 50_

**Line 74**
`std.debug.print("{s} {!s} / ", .{ first_line1, first_line2 });`

**Comment by ratfactor** [comment]
@timos-komni 

Yup! This has been fixed: https://github.com/ratfactor/ziglings/pull/116
Please let me know if you still have issues after updating or any other problem. Thanks!
