### ISSUE TITLE
Excercise 047 has mis-matched comment to code (mutable self)

### ISSUE THREAD

**Issue by ratfactor** [ratfactor/ziglings#126]
Thanks to @unional for pointing out that the comment and code on Ex 047 do not match, which is super unfortunate.  The comment shows an instance where we don't need a mutable reference. The code uses a `self: *foo` reference since it _does_ need to be mutable.

There may be other instances where this has happened.  Probably better check every instance of `self` in the Ziglings exercises to make sure this is being used consistently.

Re: #123

**Comment by hippietrail** [comment]
I know I was confused by the `self`s in the exercises and was never sure whether I should've been using `*` or not. Maybe that was the result of it being inconsistent?
