### ISSUE TITLE
Exercise 57: metaphor issue - the bee doesn't die!

### ISSUE THREAD

**Issue by unional** [ratfactor/ziglings#127]
Only `ant` can be `.still_alive = true`. 🤣 

https://youtu.be/_5YbPhOFC20?t=1682

**Comment by ratfactor** [comment]
@unional Ha ha, you're right. :rofl:  :bee: :ant: 

I should have the ants store something a bee _wouldn't_ have!

**Comment by chrboesch** [comment]
Ants collect milk from aphids, for example. To do this, they hold them similar to a sheep herd. So one possibility would be the ant remembers on which leaf it was already during the day.
