### ISSUE TITLE
Exercise 80: Correctly solved exercise produces incorrect output on latest Zig version

### ISSUE THREAD

**Issue by chrboesch** [ratfactor/ziglings#130]
Compiled with `zig version 0.10.0-dev.3672+cd5a9ba1f` gives this output:
```
----------- Expected this output -----------
[Circle(i32): 25,70,15] [Circle(f32): 25.2,71.0,15.7]
----------- but found -----------
[080_anonymous_structs.Circle(i32): 25,70,15] [080_anonymous_structs.Circle(f32): 25.2,71.0,15.7]
```
That seems the same failure in printing the type like #128

**Comment by ScottFreeCode** [comment]
Seems like it would be valuable to learn how to use it, but the design for typeName specifically may have to update what it's expected to look like, and if there's a way to get just the name without the containing path then that would be preferable for some of these exercises' designs.

**Comment by ratfactor** [comment]
@ScottFreeCode Agreed. Obviously, the string could be manipulated, but that feels fragile and I hate to add the distracting extra complexity if it can be helped.

**Comment by chrboesch** [comment]
I wonder what the reason for this new function is. Because with types like u32 it works as expected. Only not with struct. I'm trying to find a hint in the developer group, unfortunately unsuccessful so far. :neutral_face:

**Comment by chrboesch** [comment]
Ah, docu was updatet:
old
```
@typeName
This function returns the string representation of a type, as an array. It is equivalent to a string literal of the type name. 
```
new
```
@typeName
This function returns the string representation of a type, as an array. It is equivalent to a string literal of the type name.
The returned type name is fully qualified with the parent namespace included as part of the type name with a series of dots. 
```
That means  filename is the parent name space.

**Comment by chrboesch** [comment]
One suggestion for this problem could be: 
```
    if (T == Narcissus) {
        print("That's right, T = Narcissus\n", .{});
    } else {
        print("No, this type isn't correct\n", .{});
    }
```
It's just not as elegant anymore. :no_mouth:

**Comment by ScottFreeCode** [comment]
If the API is that dots separate the namespace, it feels fairly safe to me to take the last name after the dots when that's what's wanted. They could change the format, but… well they already did, so it's not like it was "safe" without string logic. :)

I guess the more philosophical question is, what is the intended use of typeName. If it's for metaprogramming then I'd want to learn the way it's "supposed" to be used. If it's purely informative, maybe exercises should frame it as such and avoid it for programmatic checking of things (except, of course, checking exercises that are merely about informative output), even if that's a little more awkward.

I might be either stating the obvious or overthinking the whole thing, of course.

**Comment by ratfactor** [comment]
Okay, I went for the stupid option for this one too. (Just like: https://github.com/ratfactor/ziglings/issues/120)

```
// Perhaps you remember the "narcissistic fix" for the type name
// in Ex. 065? We're going to do the same thing here: use a hard-
// coded slice to return the type name. That's just so our output
// look prettier. Indulge your vanity. Programmers are beautiful.
fn stripFname(mytype: []const u8) []const u8 {
    return mytype[22..];
}
// The above would be an instant red flag in a "real" program.
```
