### ISSUE TITLE
Automatic progression is a slight useability issue

### ISSUE THREAD

**Issue by mlawren** [ratfactor/ziglings#15]
Running `zig build 0X` can produce errors (or not) for the current exercise. When the exercise succeeds however it progresses immediately to the next one and so the screen fills with errors again. I find two issues here:

1. Although there is some green to indicate success, my initial reaction is that the exercise failed. I have lots of text to parse to work out what happened. In my mind `zig build $TARGET` is equivalent to `make $TARGET` which generally only indicates success or not and then stops.
2. I've asked to build something, but depending on the outcome it ends up also building something else. This is unexpected. I may or may not want to re-edit and play around with the current exercise before moving on.

Perhaps something like (just guessing here) `zig build` could use auto progression and `zig build $TARGET` could stop after success? Or at least `zig build $TARGET` should only run the next compilation after a "SUCCESS! Continue to exercise $TARGET+1? [Y/n]" or similar prompt.

p.s. Thanks for your hard work so far!

**Comment by ratfactor** [comment]
You know, that's even caught me by surprise and you would think I would have changed that behavior by now. 😆 

I completely agree with your reasoning and suggestions. I'm still new to the capabilities of Zig build scripts, so I'd like to implement it in two phases:
1. Halt after checking the exercise when a specific exercise was requested
2. Prompt to continue

I'd also like to make it more obvious when you've gotten one right for the first time in the normal progression as well. Especially when you've only done one or two, the success feels completely drown out by the verbosity of an error.

If anyone reading this has any ideas (or patches) for improving this, I'd love to hear them.

**Comment by ratfactor** [comment]
I've made "check and halt" the default action when you check a specific exercise like so:

```
zig build 01
```

The previous "start here and continue" behavior is still available as:

```
zig build 01_start
```
