### ISSUE TITLE
Ziglings collaborator wanted! (Comes with shirt.)

### ISSUE THREAD

**Issue by ratfactor** [ratfactor/ziglings#151]
Howdy! I'm still around. I have a few other things in my personal queue before I can get to issues and PRs here. I will get to them eventually, but in the meantime, I'm wondering if anyone would be interested in being a **collaborator on the Ziglings repo**? 

Especially when there's "obviously correct" fixes for changes to the core language or Zig standard library, everyone has been super cool about helping out and **I'm the one holding up the works**!

A collaborator would need to be comfortable testing and accepting PRs for language changes that break exercises or the Ziglings build script. You will be a *Ziglings Merginator!!!*  (Disclaimer: you may or may not also notice additional powers such as the ability to understand lizards, degauss CRT monitors by touch, and shut down the Internet of Things with a single spoken word.)

Oh, and I hope it goes without saying that a Ziglings collaborator would also need to be totally nice and welcoming to everyone, especially newbies to Zig, Git, and/or Github processes.

After three months of successful service, my collaborator will get an official Ziglings Merginator t-shirt (design pending) so that people on the street will know how powerful you are.

**Comment by chrboesch** [comment]
I would try it, I collect T-Shirts ;-) and I love magic skills! Also, I moderated forums for years, so that would fit. Only the invention of stories is a little lacking. But fortunately, you've laid a good foundation there.

**Comment by chrboesch** [comment]
> Between work and family, I just really can't plan but a few tiny pockets of my time, and I try not to spend those on the Internet. I guess it's a perfect example of why I need a collaborator in the first place!

No problem, we all have this challenge and therefore we divide the work. :smiley:

**Comment by ratfactor** [comment]
@chrboesch Just wanted to say, thank you so much for taking this on. I've seen the flurry of activity. There's no way I would have been able to keep up with it right now. I'm finishing up the art project at the end of this month and will be able to start on that sweet t-shirt! :grinning:

**Comment by chrboesch** [comment]
Thank you, I like doing it and it gives me a lot of pleasure. And no hurry with the T-shirt, we still have winter. :wink:

**Comment by ratfactor** [comment]
Oh looks like I didn't mention this: January's art project is done, but February has _also_ had a (sort of) surprise deadline as well. I knew I was giving a talk, but I didn't know when it would be scheduled. I'm drawing all of the slide content. Because I like pain. Ha ha. Anyway, March should be wide open for sweet shirt design action. :fire: :shirt: :fire:

**Comment by chrboesch** [comment]
I can understand why you have to do something like that. I find your pictures, especially those with watercolor, very beautiful. And by the way, this is one of my paintpoints for lectures, I miss this kind of creativity. Then I always resort to something like PlantUML. :wink:

**Comment by ratfactor** [comment]
I made it just under three months! You've been doing awesome. There's no way I'd be able to keep up with all of this activity lately. 

Hope you like the design.

Black BG:

![ziglings2023_800](https://user-images.githubusercontent.com/1458409/229385105-2aa49c6b-1b7e-4a48-9ca7-1446330969a3.png)

White BG:

![ziglings2023_800w](https://user-images.githubusercontent.com/1458409/229385155-cb2506fa-e3f4-419a-96a9-683cac755431.png)

Do you have a shirt color preference?

**Comment by ratfactor** [comment]
I'm printing up a test one right now. Here's what the preview looks like on **"charcoal black"** (very dark gray), which I  like:

![blackshirt](https://user-images.githubusercontent.com/1458409/229385469-baf35d55-2b57-41be-8644-9536d73a2881.png)

**Comment by chrboesch** [comment]
Mega! :smile:

**Comment by chrboesch** [comment]
> Here's what the preview looks like on **"charcoal black"** (very dark gray), which I like:

I like it too! :+1:

**Comment by ratfactor** [comment]
Awesome. Now I just have to get it to you. We should have each other's email addresses by now anyway. Here's how you can get mine:

```
$ cd ziglings
$ git show 4634f23555c0848289dcf3df0cf1bb1b1485bd8b
```

:smiley:

**Comment by chrboesch** [comment]
E-Mail is on its way.

**Comment by chrboesch** [comment]
The wonderful T-Shirt hast arrived, and my joy accordingly great!  That closes this issue. 
Many thanks to Dave, for the idea of  Ziglings and the opportunity to participate. :smile:
