### ISSUE TITLE
Easy interfaces with Zig v0.10

### ISSUE THREAD

**Issue by chrboesch** [ratfactor/ziglings#153]
Since Zig version 0.10 it is possible to create simpler interfaces, see: [Easy Interfaces with Zig 0.10.0](https://zig.news/kristoff/easy-interfaces-with-zig-0100-2hc5) I think that it is worth to make another excercise for it. Since I have already actively used this option in a program, I would program that for ziglings. :smiley: I wouldn't put it under "unions," but rather under a new heading called "interfaces."

**Comment by chrboesch** [comment]
@ratfactor I made a draft for this exercise based on the idea of exercise 55-57, with an additional character, a grasshopper. I was thinking of a kind of "list of my garden friends", who automatically give a status every day. An interface would be a good fit for this. Now all that's really missing is the text: your part.

**Comment by ratfactor** [comment]
@chrboesch Ooh, sounds great! I'll start reading through Loris Cro's article (I wanted an excuse to do that anyway). Do you have a branch with the new exercise I could look at? Thanks!

**Comment by chrboesch** [comment]
Here it is: https://github.com/chrboesch/ziglings/blob/interfaces/exercises/092_interfaces.zig

**Comment by chrboesch** [comment]
@ratfactor What does the 'eyes emoji' means?

**Comment by ratfactor** [comment]
@chrboesch It means (at least I think so) "saw this" and/or "I'll take a look at this."

**Comment by ratfactor** [comment]
I skimmed it once through and looks great! I'll go through more carefully and see if I can come up with a good explanation/story. :smile:

**Comment by chrboesch** [comment]
Great, from my point of view, this is the most difficult part. :relaxed:
