### ISSUE TITLE
Exercise 64 - changed @addWithOverflow signature

### ISSUE THREAD

**Issue by eh4** [ratfactor/ziglings#156]
Using zig 0.11.0-dev.1301+0e659042a I ran into the issue that @addWithOverflow takes 2 arguments instead of 4. 

Original:

    var my_result: u4 = undefined;
    var overflowed: bool = undefined;
    overflowed = @addWithOverflow(u4, a, b, &my_result);

My replacement:

    var my_result: u4 = undefined;
    var overflowed: bool = undefined;	
	const of_struct = @addWithOverflow(a,b);
	my_result = of_struct[0];
	overflowed = of_struct[1] == 1;

Since I'm still learning I hope that someone can come up with a prettier way to write that. Otherwise I had to look up the [0] and [1] syntax for anonymous struct so might have to add a note about that? I don't think it's mentioned in the earlier exercises

**Comment by chrboesch** [comment]
@eh4 Thank you!
