### ISSUE TITLE
066_comptime.zig

### ISSUE THREAD

**Issue by heretique** [ratfactor/ziglings#172]
Excercise 66 has a small issue in that it expects `var_int` and `var_float` to be `u32` and `f32` respectively but `u16`, `f16` or wider types are all correct given the values of the variables.

**Comment by chrboesch** [comment]
Right. Do you think we should change the expected variables to u16 and f16?

**Comment by chrboesch** [comment]
I think making the description more precise should work.

**Comment by chrboesch** [comment]
@heretique Thank you for this hint.
