### ISSUE TITLE
"99 is enough for anybody" (I only zero-padded two digits)

### ISSUE THREAD

**Issue by ratfactor** [ratfactor/ziglings#18]
Rather than hem and haw about it in the beginning, I went ahead and started these with two digit padding.  But at this rate, I might run out of two-digit numbers before I'm even done with the language itself, let alone the standard library!

```
01_hello.zig
02_std.zig
...
98_unfragulating.zig
99_unfragulating2.zig
```

The other problem is inserting new items. Changing the order of items is even worse, but obviously won't ever be needed because this order is objectively perfect as is. 😆 

I thought about leaving the exercises un-numbered, which would allow me to change the order or insert new topics easily.  But I really like the fact that you can go into the exercises directory and see the order plain as day.

### Triple Digit Number Options:

1. When I hit 100, go ahead and call it `100_foo.zig` and it'll alpha-sort between 09 and 11 or
2. When I hit 100, rename 01-99 to 001-099 and assume there will never be more than 999 ziglings.

If the filenames are to be triple-digit, I'd rather bite the bullet sooner rather than later.

### Move/Insertion Options:

1. If something needs to be inserted, number it with a decimal: `12.1_while2.1.zig` or
2. Renumber everything after the inserted item.

I have a strong aversion to _renumbering_ anything at any time because it will screw up existing written references to specific exercises (in commits and mentions internal or external to the project).  In general, I really like the ability to refer to the exercises by absolute number and being able to count on that not changing.

**Comment by lukeholder** [comment]
Move to 4 digits now. Better sooner than later. There may be 1,000 but there will never be 10,000 :)

**Comment by ratfactor** [comment]
@lukeholder Ha ha, thanks for the input. I think you're right, it needs to be done and soon.

In addition to renaming the files, I think the build script that controls all of this should understand/allow exercise numbers without leading zeroes as input from the user. I don't personally mind typing `01` through `09`, but I draw the line at `001` through `099`. :-)

I'll look into this soon and when I'm ready, I'll add another comment. Anybody else who happens to read this is welcome to claim the work if I haven't yet!

**Comment by ratfactor** [comment]
It is done.  Now we meditate.

☁️ 000 🌩️
