### ISSUE TITLE
Sentence structure seems wrong

### ISSUE THREAD

**Issue by vishalsodani** [ratfactor/ziglings#19]
Hi,

In this file https://github.com/ratfactor/ziglings/blob/main/exercises/19_functions2.zig, the sentence is 

> Here's an
// example that takes two parameters. As you can see, parameters
// are declared just like an other types ("name": "type"):

I am not sure if "**like an other types**" is what was intended. Should it be "**like any other types**" ?

**Comment by ratfactor** [comment]
It sure should! Thanks for catching this. I'll have a fix up soon!

**Comment by vishalsodani** [comment]
Thanks for making this. Yesterday afternoon was a joyous experience  as I did the exercises.

**Comment by ratfactor** [comment]
Wow, that's awesome to hear! Thank you very much for that.
