### ISSUE TITLE
Memory allocation example

### ISSUE THREAD

**Issue by Seanny123** [ratfactor/ziglings#193]
As someone coming from Python, the most important difference with Zig is it's manual memory management. I would like to propose adding an example of memory allocation.

I think it could be introduced after `manypointers`?

For the example, how about getting a running average of an array and saving the result in a new array? We would have to pretend the input array is only known at run-time via user input, but would that be a reasonable conceit?

**Comment by Seanny123** [comment]
I'm now realizing this goes against the stated "to limit Ziglings to the core language and not attempt coverage of the Standard Library". I'll make a draft PR anyways and you can decide whether it's worth including.

**Comment by ratfactor** [comment]
:+1:  I should probably re-word that statement.  I have no problem with Standard Library exercises on _principle_. I just want to limit the amount of Ziglings churn as we attempt to keep up with the Zig master branch!

The stdlib is known to change even more rapidly than the core language (and that's saying something). But some topics are so important, they're probably worth the effort of upkeep.
