### ISSUE TITLE
Exercise 58 contradicts README.md's 1st paragraph

### ISSUE THREAD

**Issue by ffunenga** [ratfactor/ziglings#198]
The first paragraph in [ziglings/README.md](https://github.com/ratfactor/ziglings/README.md) reads (bold added herein):

> Welcome to Ziglings! This project contains a series of **tiny** broken programs. (...)

However, in [exercise 58](https://github.com/ratfactor/ziglings/tree/main/exercises/058_quiz7.zig), the following is observed:
* exercise 58 has 472 lines of code
* [line 35](https://github.com/ratfactor/ziglings/blob/main/exercises/058_quiz7.zig#L35) "This is a very big example."
* [line 258](https://github.com/ratfactor/ziglings/blob/main/exercises/058_quiz7.zig#L258) never-before-seen syntax firstly introduced in the middle of the exercise: `(...).?.place`.

**Comment by ratfactor** [comment]
:+1: I agree! Ex 058 is a departure from the smaller exercises and you're not the first person to dislike it.

Issue #125 was also about this, but I've not made the time, personally, to replace the longer exercises with shorter ones. I'd love a suggestion for a replacement - probably something less ambitious than a zero-allocation path-finding program. :laughing:

**Comment by chrboesch** [comment]
I think we should change the sentence `...a series of tiny broken programs.. ` into `..a series of tiny and some bigger programs...`. :sweat_smile:
