### ISSUE TITLE
o

### ISSUE THREAD

**Issue by xyproto** [ratfactor/ziglings#2]
Hi,

I just wanted to say that the `o` editor is a great fit for solving the ziglings exercises.

When editing ie. `03_assignment.zig`, it's possible to just press `ctrl-space` and the cursor will jump to the problematic location, while the error message is displayed at the bottom of the screen. It is intended to help lowering the threshold of getting started with Zig.

The `o` editor is configuration-free.

I guess this is a feature request for mentioning `o` in the README, if you should happen to like it.

* The [`o` editor](https://github.com/xyproto/o).

Thanks for making the ziglings exercises!

Best regards,
Alexander F. Rødseth

**Comment by ratfactor** [comment]
That's a really nice feature. The `ziglings` executable isn't in its final form yet. (I'd like it to be written in Zig.)

```
<"This Isn't Even My Final Form" meme goes here>
```

So it's not quite ready to have setup recommendations. However, I could definitely see having a "Editor/Setup Recommendations" section in the readme, particularly general tips for popular editors to speed things along. I'll close this for now. Thanks for your feedback!
