### ISSUE TITLE
Exercise 70: struct methods' self parameter has wrong type

### ISSUE THREAD

**Issue by ZoloZithro** [ratfactor/ziglings#205]
The first parameter `self` in the struct methods `waddle` and `connect` should be a pointer to a struct and not a struct itself, since we want to mutate `self`; three methods total need correcting.

Not 100% sure though; it compiles fine if they aren't used, but if you make `ducky1` a `var` and call `ducky1.waddle(1,1)` it won't compile with the expected error.

Maybe this is a Zig bug? Or it just doesn't care about it unless you use it?

**Comment by chrboesch** [comment]
> Maybe this is a Zig bug? Or it just doesn't care about it unless you use it?

Neither. Zig tries to make it safe. A constant is always safer than a variable. As long as you don't want to change anything you should use a constant.

**Comment by ZoloZithro** [comment]
> As long as you don't want to change anything you should use a constant.

Now I'm more puzzled; what follows is the `waddle` method from the `Duck` struct:
```
    fn waddle(self: Duck, x: i16, y: i16) void {
        self.location_x += x;
        self.location_y += y;
    }
```

Isn't this trying to change the immutable variable `self`?

**Comment by chrboesch** [comment]
This function is only dummy code in this exercise and yes, you are absolutely right: if you call it you get an error.

**Comment by chrboesch** [comment]
@ZoloZithro Changed it, thanks for this hint! :smile:

**Comment by ZoloZithro** [comment]
@chrboesch the struct method `connect` for `Duct` has the same issue.

**Comment by chrboesch** [comment]
@ZoloZithro Thanks again!
