### ISSUE TITLE
build: incorrect description of the named_install step

### ISSUE THREAD

**Issue by perillo** [ratfactor/ziglings#213]
Currently, the `named_install` step is defined as:
```zig
const named_install = b.step(b.fmt("{s}_install", .{key}), b.fmt("Install {s} to zig-cache/bin", .{ex.main_file}));
```

However the executable, by default, is installed in `zig-out/bin`, not `zig-cache/bin`.
Moreover, the user can change the destination, with the `-p` `--prefix` or `--prefix-exe-dir` options.

I will fix it.

By the way: is it really necessary to add an install step?

**Comment by chrboesch** [comment]
> By the way: is it really necessary to add an install step?

No, if you can do without, that's fine too.
