### ISSUE TITLE
Build: some steps don't show the ziglings logo

### ISSUE THREAD

**Issue by perillo** [ratfactor/ziglings#214]
The *named_test* (`zig build 1_test`), *named_install* (`zig build 1_install`) and *named_verify* (`zig build 1`) steps don't show the *Ziglings logo*.

@ratfactor, @chrboesch Is this behavior intentional?

Thanks.

**Comment by chrboesch** [comment]
The Ziglings logo is actually only displayed when `zig build` is started. I have changed this in the current version so that the logo no longer showed as a step but with `debug.print`.

**Comment by perillo** [comment]
In 9354de0 I restored the previous behavior.  Is it ok?

Whether the logo is shown depends on how the dependencies are defined.  Using `debug.print` the logo is always shown, including when showing the build usage help.

**Comment by chrboesch** [comment]
>  Is it ok?

Yes, of course!
