### ISSUE TITLE
README.md: add the full zig version to the latest required version

### ISSUE THREAD

**Issue by perillo** [ratfactor/ziglings#221]
Currently, the last version of the Zig compiler know to work is formatted as `0.11.0-dev.2157+xxxxxxxxx`.

While the revision number is convenient for users, it is not convenient for collaborators.

When changing the code, you need to check if the latest supported version still work, and you need the exact commit in order to build a stage4 compiler to use for the check.

I suggest to use the full `zig version`, for the last know supported Zig compiler.  In the change history it is ok to keep the current format.

**Comment by drbeco** [comment]
Dear @perillo , I believe this issue is related #336 . Thanks for looking into it.
