### ISSUE TITLE
Adjustment of the 'Advanced usage' in the README

### ISSUE THREAD

**Issue by chrboesch** [ratfactor/ziglings#223]
The ['advanced usage'](https://github.com/ratfactor/ziglings/blob/main/README.md#advanced-usage) still needs to be adjusted, both in the build system and in the readme.

**Comment by perillo** [comment]
It is already working in the build system; only the `README.md` file needs to be updated.

Unfortunately, I missed the *Advanced Usage* section in commit 0d56ba3; sorry for the inconvenience.

**Comment by chrboesch** [comment]
see https://github.com/ratfactor/ziglings/pull/212#issuecomment-1500540079
