### ISSUE TITLE
deprecation of `Build.run` and `Build.install`

### ISSUE THREAD

**Issue by perillo** [ratfactor/ziglings#231]
See ziglang/zig@1728d92.

I will try to update it as soon as possible.

**Comment by chrboesch** [comment]
Yes, I have read.

**Comment by perillo** [comment]
@chrboesch I'm updating the *Version Changes* section in the `README.md` file, but what should I write to comment the change in the current version 0.11.0-dev.2401 (2023-04-07)?

**Comment by chrboesch** [comment]
fixes of the new build system

12.04.2023 18:28:00 Manlio Perillo ***@***.***>:
