### ISSUE TITLE
Error on first exercise `Unable to spawn 001_hello: FileNotFound`

### ISSUE THREAD

**Issue by mikowitz** [ratfactor/ziglings#236]
From a fresh checkout of this repo, after correcting the error in the first exercise and running `zig build`, I am given the following error output:

```
Compiling 001_hello.zig...
Checking 001_hello.zig...
Unable to spawn 001_hello: FileNotFound

HINT: DON'T PANIC!
Read the error above.
See how it has something to do with 'main'?
Open up the source file as noted and read the comments.
You can do this!
Edit exercises/001_hello.zig and run this again.
To continue from this zigling, use this command:
    zig build -Dn=1
error: the following build command failed with exit code 1:
/Users/mikowitz/Code/ziglings/zig-cache/o/ff08cd9d949daaad044fdbd333fd6718/build /Users/mikowitz/.asdf/installs/zig/master/zig /Users/mikowitz/Code/ziglings /Users/mikowitz/Code/ziglings/zig-cache /Users/mikowitz/.cache/zig
```

The executable `001_hello` does exist in the root of the `ziglings` checkout, and I can run it via `./001_hello` and get the correct output, but I have not been able to figure out why the `build` command is failing.

I'm running:
zig version: zig 0.11.0-dev.2560+602029bb2, installed via ASDF
OS: macOS 12.6 on an M2 chip

**Comment by chrboesch** [comment]
We are working on the new build system because of the changes in Zig. I checked in a new version a few minutes ago. Can you please try it again, because I can't find the error.

**Comment by chrboesch** [comment]
@perillo fyi

**Comment by mikowitz** [comment]
Having pulled the latest and running `zig build` I'm now getting a different error:
```
error: unrecognized parameter: '--enable-cache'
001_hello.zig: The following command exited with error code 1:
/Users/mikowitz/.asdf/installs/zig/master/zig build-exe /Users/mikowitz/Code/ziglings/exercises/001_hello.zig --cache-dir /Users/mikowitz/Code/ziglings/zig-cache --enable-cache
```

Commenting out the [line that adds that parameter](https://github.com/ratfactor/ziglings/blob/main/build.zig#L826), I'm still seeing the same behaviour as originally reported. I'll be able to test this on a different laptop a bit later this afternoon just in case there is something wonky about the one I'm on currently.

**Comment by chrboesch** [comment]
@mikowitz Could you try `zig build -Dn=1` this should produce the right error.

**Comment by perillo** [comment]
> Having pulled the latest and running `zig build` I'm now getting a different error:
> 
> ```
> error: unrecognized parameter: '--enable-cache'
> 001_hello.zig: The following command exited with error code 1:
> /Users/mikowitz/.asdf/installs/zig/master/zig build-exe /Users/mikowitz/Code/ziglings/exercises/001_hello.zig --cache-dir /Users/mikowitz/Code/ziglings/zig-cache --enable-cache
> ```

`--enable-cached` was removed in ziglang/zig@c96cb98ad.

I missed it.  I need to investigate how to update the code in `build.zig`

**Comment by perillo** [comment]
When `--enabled-cached` is set, the compiler prints to stdout the path to the generated executable.
Now it is no longer possible, so the code should be update.

**Comment by hacklash** [comment]
`zig build -Dn=1` repeats the same thing except without the ziglings logo. I fixed 001_hello.zig and did `run .\exercises\001_hello.zig` and it works fine, printing hello world.

**Comment by MrMarble** [comment]
I just started learning Zig, so this may be wrong, but removing the `--enabled-cache` argument and adding the cwd to the executable path works for me:

```diff
diff --git a/build.zig b/build.zig
index 4ccf9c2..b6a0594 100644
--- a/build.zig
+++ b/build.zig
@@ -728,7 +728,7 @@ const ZiglingStep = struct {
 
         const cwd = self.builder.build_root.path.?;
 
-        const argv = [_][]const u8{exe_file};
+        const argv = [_][]const u8{std.fs.path.join(self.builder.allocator, &[_][]const u8{ cwd, exe_file }) catch unreachable};
 
         var child = std.ChildProcess.init(&argv, self.builder.allocator);
 
@@ -823,8 +823,6 @@ const ZiglingStep = struct {
         zig_args.append("--cache-dir") catch unreachable;
         zig_args.append(builder.pathFromRoot(builder.cache_root.path.?)) catch unreachable;
 
-        zig_args.append("--enable-cache") catch unreachable;
-
         const argv = zig_args.items;
         var code: u8 = undefined;
         const output_dir_nl = builder.execAllowFail(argv, &code, .Inherit) catch |err| {
```

**Comment by gabstv** [comment]
After MrMarble's fix (above), I added these `.gitignore` patterns to avoid committing the binaries:
```
[0-9][0-9][0-9]_*
![0-9][0-9][0-9]_*.zig
```

**Comment by perillo** [comment]
The solution is to use Zig IPC (https://github.com/ziglang/zig/blob/master/lib/std/zig/Client.zig) to send a command to the compiler to get the path to the executable.

See https://github.com/ziglang/zig/blob/master/lib/std/Build/Step.zig#L278.

I'm working on this issue.
