### ISSUE TITLE
Disabled exercises 84-92 should probably have warning text at the top

### ISSUE THREAD

**Issue by Interrupt** [ratfactor/ziglings#240]
The async exercises have currently been removed from the build due to changes in the Zig compiler. This threw me for a loop at first until I looked at the build file. That information should probably also be at the top of each of the async files for now as well, telling people they have been disabled for now.

**Comment by chrboesch** [comment]
First, we have an issue about that: https://github.com/ratfactor/ziglings/issues/163
Second, the async functions will be back in the next days. Andrew is hard working on it.

**Comment by perillo** [comment]
> The async exercises have currently been removed from the build due to changes in the Zig compiler. This threw me for a loop at first until I looked at the build file. That information should probably also be at the top of each of the async files for now as well, telling people they have been disabled for now.

With the latest version of the code, now `zig build` will print, as an example, `Skipping 084_async.zig`.
