### ISSUE TITLE
build: add the -Dcontinue option

### ISSUE THREAD

**Issue by perillo** [ratfactor/ziglings#243]
Currently, `zig build -Dn=1 -l` shows:
```
test                         Run 001_hello.zig without checking output
zigling (default)            Check the solution of 001_hello.zig
start                        Check all solutions starting at 001_hello.zig
```

With the new option, `zig build -Dn=1 -l` will show
```
zigling (default)            Check the solution of 001_hello.zig
test                         Run 001_hello.zig without checking output
```
and `zig build -Dn=1 -Dcontinue -l` will show
```
zigling (default)            Check all solutions starting at 001_hello.zig
test                         Run 001_hello.zig without checking output
```

I think this makes the UI more consistent.

As a side affect, the command line is much longer, but note that the user doesn't need to manually run the command again, unless it want to solve the exercises randomly.  On a shell with history support, you just have to press the `Up` key.

I used `continue` instead of `start`, since it describes better what the user is doing.

**Comment by chrboesch** [comment]
> I used continue instead of start, since it describes better what the user is doing.

Agree.

I watched some of these videos [(Youtube)](https://www.youtube.com/watch?v=391iJ0qGbqM) and I watched a colleague working with Ziglings. I think this is the way how the most are really use it.

Therefore it is good if `zig build` runs as smooth as possible, see also your suggestion https://github.com/ratfactor/ziglings/issues/242

**Comment by perillo** [comment]
Looking at the video and doing some tests (I usually use the cheat mode `-Dhealed` when testing), I noted that the message should be improved.  Here is an example:

```sh
$ zig build
Compiling 001_hello.zig...
steps [2/101] 001_hello.zig... LLVM Emit Object... Checking 001_hello.zig...
PASSED:
Hello world!

Compiling 002_std.zig...
exercises/002_std.zig:14:5: error: expected type expression, found '='
??? = @import("std");
    ^

Edit exercises/002_std.zig and run this again.
To continue from this zigling, use this command:
    zig build -Dn=2
```

I think this message is confusing.  When running in what I call *normal mode* (opposed to *named mode*), in order to continue you just have to type `zig build`.

**Comment by chrboesch** [comment]
> I think this message is confusing. When running in what I call normal mode (opposed to named mode), in order to continue you just have to type zig build.

Agree.

**Comment by perillo** [comment]
Looking more carefully at the code, I now think that the help message is correct.

The advantage of using `zig build -Dn=n` to continue, is that:
  - The Ziglings logo is not show (this is intentional).
  - The command will not replay the previous commands
 
Adding support for caching in `ZiglingStep` may improve calling `zig build`, but the current help message is fine and, more important, it works in all contexts (`zig build` or `zig build -Dn=n`).

I also have some doubts about adding the `-Dcontinue` option, since the help message needs to change based on the context, making the code a bit more complex.

**Comment by perillo** [comment]
This proposal is no longer necessary after #300.

Now `zig build -l` will show:
```
  ziglings (default)           Check all ziglings
  test                         Run all the tests
  test-cli                     Test the command line interface
```

and `zig build -Dn=1 -l` will show:
```
  zigling (default)            Check the solution of 001_hello.zig
```
