### ISSUE TITLE
.gitattribute: remove old entries and force lf mode for python files

### ISSUE THREAD

**Issue by perillo** [ratfactor/ziglings#252]
In `gitattributes` there are entries that set attributes for (probably) old files: `.bat`, `.h` and `.cpp`.

Is it ok to remove them?

Should I add an entry `*.py text eol=lf` for python files?

**Comment by chrboesch** [comment]
> Is it ok to remove them?

I think so.

> Should I add an entry *.py text eol=lf for python files?

Why you wrote these in Python and not Zig or Bash?
