### ISSUE TITLE
windows-latest freeze when running jobs

### ISSUE THREAD

**Issue by perillo** [ratfactor/ziglings#266]
The problem started when I added an additional job running `zig build test`.

I have done some tests on an old laptop with Windows 10.0.19044.0.
It seems the problem is Bash from  Git for Windows (I'm using PortableGit from scoop).

When running `zig build -Dhealed` from PowerShell, it works correctly.
When running `zig build -Dhealed` from Bash, sometimes it freeze, and sometimes it prints:
```
      0 [sig] patch 1829 wait_sig: garbled signal pipe data nb 62, sig 1920226088
   1968 [sig] patch 1829 wait_sig: garbled signal pipe data nb 52, sig 1668571504
   2325 [sig] patch 1829 wait_sig: garbled signal pipe data nb 43, sig 1634038312
```

However I was unable to find similar problem on Internet.

I will run some tests using github actions from my clone of ziglings.

**Comment by chrboesch** [comment]
> PowerShell, it works correctly.

As far as I know the github actions uses PowerShell. That's why I am wondering about the errors in this repo.

**Comment by chrboesch** [comment]
Ok, than I was wrong.

**Comment by chrboesch** [comment]
Idea: When we split the steps for windows and linux/mac, than we could change from bash to PpowerShell. What do you think?

**Comment by perillo** [comment]
@chrboesch I think you are too fast to commit, without waiting for a review and run/check the github actions.

In #267 you tried to run a Bash script from PowerShell, and it is obviously wrong.
I ran the Eowyn workflow from my ziglings clone manually: https://github.com/perillo/ziglings/actions/runs/4830425751

The working time for windows-latest was 1m 6s, clearly suspicious.
The output from "Run Eowyn" step is simply:
```
patches/eowyn.sh
```

The script was not executed **and** PowerShell did not raise an error.

**Comment by perillo** [comment]
The cause of the problem may be https://lightrun.com/answers/httpie-httpie-hangs-up-on-git-bash-windows

**Comment by chrboesch** [comment]
> I think you are too fast to commit

You are right, sorry.
> The script was not executed and PowerShell did not raise an error.

That is bad. 

> The cause of the problem may be

I'm going to read that and try to understand how we can solve the issue.

**Comment by chrboesch** [comment]
Maybe we should go the same way as Ziglang and write a PS script?

**Comment by perillo** [comment]
After some time I finally fixed this issue; I will create a PR later.

@chrboesch I will need to update the workflows, and I noted that you added quotes to the workflow names and comments.
However I think that they are not very useful. I would like to remove the quotes and move the comments at the top of the files, improving them.  Is it ok for you?

**Comment by chrboesch** [comment]
> and I noted that you added quotes to the workflow names and comments.
However I think that they are not very useful

According to gihub documentation, this is how you are supposed to do it.

**Comment by perillo** [comment]
> > and I noted that you added quotes to the workflow names and comments.
> > However I think that they are not very useful
> 
> According to gihub documentation, this is how you are supposed to do it.

The workflow file uses the YAML format, so quoting is not necessary, unless you need to force a builtin type like `int` or `bool` to a `string`.
