### ISSUE TITLE
Exercise 102 shall be for testing

### ISSUE THREAD

**Issue by chrboesch** [ratfactor/ziglings#277]
Testing in Zig is important and I would like to create an exercise for it. But the challenge is to extend our build system to include a test step that we can turn on with a new flag `test_run`.
I will open a PR with a simple test exercise, that we can to extend the build system.

**Comment by perillo** [comment]
The `zig test` command supports the Zig IPC; the advantage is that it will allow the use of custom colors in `ZiglingStep`.
See https://github.com/ziglang/zig/blob/3f3b1a6/lib/std/Build/Step/Run.zig#L936

The alternative is to just run `zig test`; the advantage is that we don't have to add additionally code.

**Comment by ratfactor** [comment]
Would a stand-alone executable (#296) help or hurt this effort?

**Comment by chrboesch** [comment]
> Would a stand-alone executable (https://github.com/ratfactor/ziglings/issues/296) help or hurt this effort?

We need to start a process where we run e.g. `zig test 102_testing.zig`. So it should not be as difficult as creating a test step in the current build system. Rather easier.
