### ISSUE TITLE
Unit test broken by commit dbd42bb

### ISSUE THREAD

**Issue by perillo** [ratfactor/ziglings#295]
The message "Look out! Broken programs below!" after the logo is probably incorrect, since it will be printed when all exercises have been healed, too.

Using `std.os.exit(0)` instead of `std.os.exit(1)` also broke the unit test case 5 where I test that `zig build -Dn=1` prints the hint and exits with exit status 1.

Fortunately there is a simple solution: using exit code 2:
https://github.com/ziglang/zig/blob/d70853b/src/main.zig#L4487

I'm updating the code to always use the new exit code.

The only issue remains with the compatibility check, since this special case was added in commit ziglang/zig@8acbfafef; probably it should die with exit code 0 (the `ci/compat.sh` script checks only the error message).

BTW: I'm also moving the ziglings logo definition from the `build` function scope to the global scope, making it public.  The reason is that the unit test needs to know how many lines must be skipped when the logo is printed.

**Comment by perillo** [comment]
@chrboesch ping

**Comment by ratfactor** [comment]
@perillo I'm glad there's an easy fix for the exit code.

As I mentioned in #294, the "Look out!" message is there for the initial Ziglings experience. What if we just had it appear for the first couple exercises? Is that possible?

**Comment by perillo** [comment]
@ratfactor Yes.  It should be easy, since `ZiglingStep` knows the current exercise number/key.
