### ISSUE TITLE
build: status of the special eoywn mode

### ISSUE THREAD

**Issue by perillo** [ratfactor/ziglings#297]
By *eowyn mode* I mean the code that builds all the exercises using full parallelism, without using `ZiglingStep.`
I added it in order to improve the performance of the Eoywn workflow, but I disabled it because the unit tests also use `zig build -Dhealed`.

The code can be enabled again by exporting, e.g., the `HEALED_BY_EOWYN` environment variable in the `patches/eowyn.sh` script.

A better solution is to simply remove the code, simplifying `build.zig`.

@ratfactor, @chrboesch What do you think?

**Comment by chrboesch** [comment]
@perillo I think it is not worth for a bit more speed to support different build modes. So in my opinion you can remove the code.

**Comment by ratfactor** [comment]
I agree. Deleted code is the best kind.
