### ISSUE TITLE
build: status of the install step

### ISSUE THREAD

**Issue by perillo** [ratfactor/ziglings#298]
Currently both `zig build` and `zig build -Dn=1` support the install step, and the install step is documented in the `README.md` file:
"Calling all wizards: To prepare an executable for debugging"

I'm not sure if a new Zig user will need to debug the executable, but `ZiglingStep` can just copy the executable to `zig-out`.

The advantage of removing the install step is that in *normal mode* we can remove the `build_step` step, since it was only necessary for the `install` step.  This will also make it possible to remove the use of `SkipStep`, thus simplifying the code.

@ratfactor, @chrboesch Do you think it is ok to remove the install step?

**Comment by chrboesch** [comment]
> Do you think it is ok to remove the install step?

Yes, I think so. The simpler, the better.
