### ISSUE TITLE
build: status of named mode

### ISSUE THREAD

**Issue by perillo** [ratfactor/ziglings#299]
By *named mode* I mean `zig build -Dn=n`.

Currently the code handling the *named mode* is rather complex.  In order to simplify it we can:
  1. Remove the `build -Dn=n install` step (see #298)
  2. Remove the `build -Dn=n test` step
      This will make it possible to remove the `build_step` step and the use of `SkipStep`, thus simplifying the code.
  3. Remove the `build -Dn=n start` step
      This will greatly simplify the `build.zig` file.

Only `zig build -Dn=n` step will remain, where the user needs to manually specify the exercise number.

@ratfactor, @chrboesch What do you think about removing these steps?

**Comment by chrboesch** [comment]
> Only zig build -Dn=n step will remain

I think this should be enough. Every time when I have watched someone using Ziglings, `zig build` or ` zig build -Dn=x` has been used.
