### ISSUE TITLE
Exercise 64 Builtins

### ISSUE THREAD

**Issue by srazash** [ratfactor/ziglings#306]
Hi everyone!

I'm just working my way through Ziglings and I hit a issue on exercises/064_builtins.zig, on line 82: `const tupni: u8 = @bitReverse(input, tupni);`

When running `zig build` I received this message:
```
Compiling 064_builtins.zig...
exercises\064_builtins.zig:82:23: error: expected 1 argument, found 2
    const tupni: u8 = @bitReverse(input, tupni);
```

Changing the line to: `const tupni: u8 = @bitReverse(input);` as described in the docs (https://ziglang.org/documentation/master/#bitReverse) resolved this and allowed me to complete the exercise, I update Zig every few days and the build I'm using currently is: 0.11.0-dev.3132+465272921, I'm guessing this is a recent change?

Thanks to you all for the great work you've done here, and hopefully this is of some use to the project!

**Comment by srazash** [comment]
And I've just submitted a PR for this, thanks!

**Comment by srazash** [comment]
Ignore this! Turns out I didn't read the comments in the exercise fully - how embarrassing :S

**Comment by chrboesch** [comment]
Welcome to Zoglings!

> how embarrassing

This is not bad and has also happened to me. :smile:
