### ISSUE TITLE
Exercise 47 unclear.

### ISSUE THREAD

**Issue by nihohit** [ratfactor/ziglings#315]
The obvious replacement for `???.zap(???);`, given the previous lesson, is with `heat_ray.zap(&alien);`, but it isn't the correct one. IMO this requires an explanation, or a another lesson about the combination of `for` and pointers.

**Comment by HeCorr** [comment]
The comment on line 87 states:
> // Loop through every alien **by reference** (* makes a pointer capture value)

Meaning `alien` is already a pointer.
