### ISSUE TITLE
exercise 21 fn numberFail is unclear 

### ISSUE THREAD

**Issue by Sensenman1** [ratfactor/ziglings#319]
It is unclear why I can't put "return MyNumberError.TooFour;" above the other two lines in the function. A simple comment in the exercise to explain it would be very helpful.

**Comment by chrboesch** [comment]
Because the 'if' functions do not have an else block. This is a common way, not only for Zig, to avoid 'else'.
Alternatively you could write:
```
    if (n > 4) {
        return MyNumberError.TooBig;
    } else if (n < 4) {
        return MyNumberError.TooSmall;
    } else {
        return MyNumberError.TooFour;
    }
```
Maybe this is a bit clearer for you?
