### ISSUE TITLE
doubt about using if in exercise 34

### ISSUE THREAD

**Issue by twsm000** [ratfactor/ziglings#322]
Hello, I'm learning zig through ziglings and finished exercise 34 through the result below (example 1). My doubt is, to return any value of an if expression, it's necessary to have everything in one line like a ternary operator? Because I've tried in another way (example 2) and cannot get the output. I searched in the documentation in the 'if' section, but I not found anything related.

```code
// Example 1 - Compiled successfully
const std = @import("std");

const NumError = error{IllegalNumber};

pub fn main() !void {
    const stdout = std.io.getStdOut().writer();

    return if (getNumber()) |my_num| stdout.print("my_num={}\n", .{my_num}) else |err| stdout.print("{}", .{err});
}

// This function is obviously weird and non-functional. But you will not be changing it for this quiz.
fn getNumber() NumError!u32 {
    if (false) return NumError.IllegalNumber;
    return 42;
}
```

```code
// Example 2 - Compilation error
const std = @import("std");

const NumError = error{IllegalNumber};

pub fn main() !void {
    const fmt = std.io.getStdOut().writer();

    const result = if (getNumber()) |my_num| {
        fmt.print("my_num={}\n", .{my_num});        
    } else |err| {
        fmt.print("{}", .{err});
    };
    // do something else with the result...    
    return result;

    // The compilation error:
    // 034_quiz4.zig:16:18: error: error is ignored
    // fmt.print("my_num={}\n", .{my_num});
    // ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
    // 034_quiz4.zig:16:18: note: consider using 'try', 'catch', or 'if'
}

// This function is obviously weird and non-functional. But you will not be changing it for this quiz.
fn getNumber() NumError!u32 {
    if (false) return NumError.IllegalNumber;
    return 42;
}

```

**Comment by chrboesch** [comment]
The function `getNumber` can return the value or an error. This means that you have to handle the possible error. The easiest way in this case is to call the function with a `try`: `try getNumber()` and if an error occurs, it will be passed through the main function and displayed in the terminal because `main` is declared with `!void`.

**Comment by twsm000** [comment]
But what was I trying to achieve is to get the output from the print method (Error!void). The error was handled inside the else. In the *Example 1* I've used `return if (getNumber()) |my_num| stdout.print("my_num={}\n", .{my_num}) else |err| stdout.print("{}", .{err});`  in a single line to get the output from print returned to main,  but the example below is the same thing, except that I got a compilation error. So, my doubt is the return output from if expression only works when used in a single line?

```code
pub fn main() !void {
    const stdout = std.io.getStdOut().writer();

    // This code does not compile
    return if (getNumber()) |my_num| {
        stdout.print("my_num={}\n", .{my_num});
    } else |err| {
        stdout.print("{}", .{err});
    };

    // This compiles
    // return if (getNumber()) |my_num| stdout.print("my_num={}\n", .{my_num}) else |err| stdout.print("{}", .{err});
}
```

**Comment by chrboesch** [comment]
>    // The compilation error:
>    // 034_quiz4.zig:16:18: error: error is ignored
>    // fmt.print("my_num={}\n", .{my_num});
>    // ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
>    // 034_quiz4.zig:16:18: note: consider using 'try', 'catch', or 'if'

The error message of the compiler gives you the hint: You must also handle the error that can come from `print()`:
`try stdout.print("my_num={}\n", .{my_num});`
and so on.
