### ISSUE TITLE
`var` vs `const` in exercice 025

### ISSUE THREAD

**Issue by lorrding** [ratfactor/ziglings#324]
Hi, I've been doing the exercises on this repo (it's really great btw) and I'm wondering why we're using `var`s in some exercises when we could use `const`s ?

For example here in 25:
https://github.com/ratfactor/ziglings/blob/ae343729910cc2e86bcdefd67a2a7124047c8b80/exercises/025_errors5.zig#L17-L23

I tried making `a`,`b` and `c` to constants and it compiles the same

**Comment by chrboesch** [comment]
> I'm wondering why we're using vars in some exercises when we could use consts ?

Zig is in a development mode and sometimes things changes. So it may be that in an older version of the compiler it only worked with `var` and now it also works with `const`. This exercise is about 2 years old.

**Comment by chrboesch** [comment]
Update: I tried with `zig version 0.80` and it also works with `const`. So that was not the reason. We could change that. Would you want to do that?
