### ISSUE TITLE
My personal copy of the ziglings repo is triggering Github Actions

### ISSUE THREAD

**Issue by g-berthiaume** [ratfactor/ziglings#330]
I'm not a CI/CD specialist, but I assume copying the template is also copying the auto-trigger for the pipeline.

![image](https://github.com/ratfactor/ziglings/assets/19377511/31408131-fed8-4423-92da-b1155785ecae)

**Comment by chrboesch** [comment]
That's right.

**Comment by perillo** [comment]
@g-berthiaume Note that you can disable actions in https://github.com/user/repo/settings/actions

**Comment by g-berthiaume** [comment]
Thanks @chrboesch for confirming. 

Thanks @perillo  for your suggestion.
I simply delete the the [.github/workflows/](https://github.com/ratfactor/ziglings/tree/main/.github/workflows) directory to fix the problem locally.
