### ISSUE TITLE
Ziglings for zig version 0.10

### ISSUE THREAD

**Issue by drbeco** [ratfactor/ziglings#336]
Hello guys,

I've installed the Slackware package for zig, which is currently at `0.10.1`. With that on the server ready for my students to try the language, I tried to use ziglings as a teaching tool, to no avail. It asks for zig 0.11.0-dev.

So I run `git bisect` twice, with two criteria for `git bisect good`

* zig build
*  grep -A1 "zig version" README.md 

For the first `git bisect good` , that compiled with `zig build` I got commit 4d2668b;
For the second `git bisect good` , that  checked if the README suggests zig version 0.10, I got commit 04893c7

I wonder which one would be better for running ziglings with `zig version 0.10.1`.  Ofc the more recent commit the better, but I don't have fully tested if the zig build will fail in any of all of the exercices for different reasons than the ziglings' objective for it to fail as teaching tool.

I would kindly ask if we could mark such commit with a "tag" stating that this is the recommended release for zig 0.10.1, and add a line to the `README.md` file; for not all of us will be able to run the last dev version of zig, depending on distro/environment or other requirements for the server running zig. That would help avoid such work trying to figure out which one is available for each version.

Thanks for even considering or reading this post. My best to all the community.

**Comment by drbeco** [comment]
So we have three zigling commit candidates for zig version 0.10.1:

* [ ] 4d2668b990f7b8f6196cf0022242f28bed995ab4
* [ ] 04893c72534048955eb2ec406fd1591ee08e63b2
* [ ] cea631bf7f10e0c8648f561f2f418ac3eb060901

Which one is the best option?

**Comment by ratfactor** [comment]
I really like the idea of being able to use release versions. Anything that helps automate this will be nice (sorry I missed your note in #282 , @perillo ).

Nice to see a fellow _Slackware_ user, @drbeco  :smile:

**Comment by drbeco** [comment]
We don't need much to automate it. I see this repository does not use `tags` or `releases`. 

https://github.com/ratfactor/ziglings/tags

Just add to the workflow that whenever ziglings will change the version, it should `git tag zv0.10.1` or any number, and then `git push ; git push --tags`

That way it will appear in the github tag pages, or releases, making it easy for anyone to cherrypick the version they mostly need.

---

Cool, @ratfactor ! _Slackware is life_  :heart:

**Comment by chrboesch** [comment]
> Just add to the workflow that whenever ziglings will change the version...

In a few days Zig 0.11 will be releases, then we can do that.

**Comment by mynlexi** [comment]
just for clarification, starting with the release of 0.11 we can use release versions for ziglings?

**Comment by drbeco** [comment]
Dear @chrboesch , 

Although I'm grateful you solved the issue, I believe there is a problem with the current solution that may bite your ziglings in the future.

This is a small trap: calling the version number of this project (ziglings) the same version number of the other project (zig lang).

This is because the projects will not be guaranteed to run in the same pace. For example, suppose we do a good modification of ziglings, that is still to be compatible with zig v0.11. What should we call its version for ziglings now? We cannot reuse the same version number, and we cannot use ziglings v0.11.1 because this may be the version of a future zig lang release.

Do you see the trap?

Maybe we could create a "pattern" of a standard, to mark ziglings version number. 

For example, the current version would have two numbers. Suppose zig lang is at v0.11 and ziglings is at v0.5, then we could use something like:

`git tag v0.11-ziglings-v0.5`

This means each tag would have both version numbers, and this project is then free to advance to, say, `v0.11-ziglings-v0.6`, you see?

Of course this is just an example, in order to clarify the main problem. I hope this is useful for your kind consideration.
