### ISSUE TITLE
Exercise 18 fails in new version (0.12.0)

### ISSUE THREAD

**Issue by coderloff** [ratfactor/ziglings#349]
The original `Exercise 018` is following:

```zig
//
// Functions! We've already created lots of functions called 'main()'. Now let's
// do something different:
//
//     fn foo(n: u8) u8 {
//         return n + 1;
//     }
//
// The foo() function above takes a number 'n' and returns a number that is
// larger by one.
//
// Note the input parameter 'n' and return types are both u8.
//
const std = @import("std");

pub fn main() void {
    // The new function deepThought() should return the number 42. See below.
    const answer: u8 = deepThought();

    std.debug.print("Answer to the Ultimate Question: {}\n", .{answer});
}

// Please define the deepThought() function below.
//
// We're just missing a couple things. One thing we're NOT missing is the
// keyword "pub", which is not needed here. Can you guess why?
//
??? deepThought() ??? {
    return 42; // Number courtesy Douglas Adams
}
```

Although I filled the ??? with correct values, Zig throws error. I solved it buy making main() function can throw error by adding ! before void, and I also add try keyword before deepThought() function. Here is my code:

```zig
//
// Functions! We've already created lots of functions called 'main()'. Now let's
// do something different:
//
//     fn foo(n: u8) u8 {
//         return n + 1;
//     }
//
// The foo() function above takes a number 'n' and returns a number that is
// larger by one.
//
// Note the input parameter 'n' and return types are both u8.
//
const std = @import("std");

pub fn main() !void {
    // The new function deepThought() should return the number 42. See below.
    const answer: u8 = try deepThought();

    std.debug.print("Answer to the Ultimate Question: {}\n", .{answer});
}

// Please define the deepThought() function below.
//
// We're just missing a couple things. One thing we're NOT missing is the
// keyword "pub", which is not needed here. Can you guess why?
//
fn deepThought() !u8 {
    return 42; // Number courtesy Douglas Adams
}
```

By the way, thanks a lot for exercises )

**Comment by rnpridgeon** [comment]
Since `deepThought` is returning a constant value, 42, you should return `u8` not `!u8`. The former tells the compiler that you will be returning an [unsigned, 8-bit integer](https://ziglang.org/documentation/master/#toc-Primitive-Types) the latter tells the compiler that you will be returning an [error union](https://ziglang.org/documentation/master/#Error-Union-Type) and that it should infer the error type.

**Comment by coderloff** [comment]
> Since `deepThought` is returning a constant value, 42, you should return `u8` not `!u8`. The former tells the compiler that you will be returning an [unsigned, 8-bit integer](https://ziglang.org/documentation/master/#toc-Primitive-Types) the latter tells the compiler that you will be returning an [error union](https://ziglang.org/documentation/master/#Error-Union-Type) and that it should infer the error type.

It worked, thanks a lot!
