### ISSUE TITLE
Ziglings broken by latest Master

### ISSUE THREAD

**Issue by dnotq** [ratfactor/ziglings#363]
Sorry, no account on codeberg, not going to make one just to post an issue.

Following the instructions on the website, downloaded the latest "Master" zig build.  This zig pull-request breaks ziglings `zig build`:

https://github.com/ziglang/zig/pull/17623

 `exec` has been renamed to `run`, so ziglings build.zig is broken in 3 places, lines 291, 309, and 358.

**Comment by chrboesch** [comment]
closed with [codeberg #19](https://codeberg.org/ziglings/exercises/pulls/19)
