### ISSUE TITLE
Failing compilation for 0.12.0-dev.1632+acf9de376

### ISSUE THREAD

**Issue by KoltPenny** [ratfactor/ziglings#365]
When compiling with zig version `0.12.0-dev.1632+acf9de376` the following error comes up:

```
error: struct 'child_process.ChildProcess' has no member named 'exec'
        var result = Child.exec(.{

```

Steps to reproduce:

Compile and install zig version `0.12.0-dev.1632+acf9de376`
Clone ziglings and `cd` into the ziglings directory.
Run `zig build`

This is a Fedora 39 Linux system.

**Comment by KoltPenny** [comment]
Unless this is the first test :thinking:

**Comment by chrboesch** [comment]
Please use [ziglings.org](https://ziglings.org), there you will find the correct version.
