### ISSUE TITLE
Set up GitHub mirror

### ISSUE THREAD

**Issue by rmarquis** [ratfactor/ziglings#366]
This is a follow-up of #360.

----
FYI, I did some test on my side to provide a mirror of the codeberg repo on GitHub (more of a "main" branch copy than a complete mirror, as I couldn't copy the on-going PRs from codeberg to GitHub). I've used a separate repository to host the necessary github action worflow.

* mirror: [rmarquis/ziglings](https://github.com/rmarquis/ziglings) (main branch only)
* github action: [rmarquis/ziglings-mirror](https://github.com/rmarquis/ziglings-mirror) (only requires a Personal Access Token to push the mirrored data. It updates the mirror every 12h but the time interval can be adjusted)

Ideally, you would host such a repo under the `ratfactor` username (instead of my own), so you'd keep entire control over that mirror. If you integrate the GH workflow file directly in the codeberg repo, you'd also don't need a separate repo as I needed (I couldn't host a file that is not on the primary source in the mirrored repo itself).

Also, I understand the codeberg repo has now diverged from this one, and this situation likely never be "fixed". You still probably want to set this repository as read only, to avoid even more confusion and more people opening tickets and PRs here instead of the new repo on codeberg.

**Comment by chrboesch** [comment]
Now we have a github mirror: https://github.com/ziglings-org/exercises

**Comment by rmarquis** [comment]
Nice. Is it updated automatically? What is the sync delay with the main repo?

**Comment by chrboesch** [comment]
It's updated daily and additionall after each merge.

**Comment by rmarquis** [comment]
I checked both GitHub and Codeberg repo, on any branch. Is the sync done automatically?

**Comment by chrboesch** [comment]
> Is the sync done automatically?

Yes, in Codeberg there are the 'Mirror Settings' under 'Repository Settings' where you can configure that.

**Comment by rmarquis** [comment]
Perfect! Many thanks.
