### ISSUE TITLE
Adding JSON & Hashmap Ziglings

### ISSUE THREAD

**Issue by saginadir** [ratfactor/ziglings#373]
I really enjoyed doing all the exercises but I was missing exercises relating to JSON & Hashmaps.

I was wondering if the project will accept PRs in which some exercises will be added in the following topics:

[ ] Parsing JSON strings to structs
[ ] Parsing JSON strings to a hashmap
[ ] Parsing struct to JSON string
[ ] Parsing hashmap to JSON string

**Comment by chrboesch** [comment]
> I was wondering if the project will accept PRs

Only on Codeberg: https://ziglings.org
