### ISSUE TITLE
Exercise 38: The printed "Expected" output and actual answer are inconsistent

### ISSUE THREAD

**Issue by jakeisnt** [ratfactor/ziglings#41]
Introducing a slight typo into exercise 38 produces this output:
```
----------- Expected this output -----------
Character 2 - G:10 H:100 XP:20
----------- but found -----------
Character 1 - G:20 H:100 XP:10
Character 2 - G:10 H:100 XP:2

-----------
```

When, really, the printout should be this based on the expected answer:
```
----------- Expected this output -----------
Character 1 - G:20 H:100 XP:10
Character 2 - G:10 H:100 XP:20
----------- but found -----------
Character 1 - G:20 H:100 XP:10
Character 2 - G:10 H:100 XP:2

-----------
```

**Comment by ratfactor** [comment]
:+1:  Thank you for bringing this up!  I was originally matching just the most vital portions of the "correct" answer, thinking it would be less strict...but I eventually realized that showing anything other than the _exact_ expected output was seriously misleading. :frowning:

I'll correct this and also look for any others I might have missed.

**Comment by jakeisnt** [comment]
I get it! Could go either way. Thanks for all of the effort you put into this - got me started on zig in just over an hour :   )

**Comment by ratfactor** [comment]
@jakeisnt That's really great to hear! Thanks again for the issue.
