### ISSUE TITLE
Unclear why garbage values are what they are in 38

### ISSUE THREAD

**Issue by AtomToast** [ratfactor/ziglings#43]
Hey, thanks a lot for the ziglings! They really are helping me get started.

In zigling number 38 you mention

```
    // Feel free to run this program without adding Zump. What does
    // it do and why?
```

For me it was unclear why exactly the garbage values are what they are. (2863311530, 170 and 2863311530).

So I went out and looked a bit to discover that they are basically just filled with 0xAAAAAA...

Then someone in the zig matrix room sent me the link to [the zig documentation](https://ziglang.org/documentation/master/#undefined), clarifying why exactly this was the case

According to your contribution guidelines ziglings should be self contained, which this broke for me.

That is unless I missed something in an earlier zigling that explained this.

**Comment by ratfactor** [comment]
You're absolutely right. I need to add a note that clarifies this. Thank you!

**Comment by ratfactor** [comment]
@AtomToast Clarification added at the end of the exercise. Thanks again for pointing this out!

**Comment by endrin** [comment]
I came here to ask the same question because I didn't read to the end of exercise... Thanks for adding this clarification and nice choice of placeholder bytes on the zig team side 😏

**Comment by ratfactor** [comment]
> I came here to ask the same question because I didn't read to the end of exercise.

Hmm...I wonder if I need to draw attention to the end-of-exercise notes?  Glad you found it!
