### ISSUE TITLE
Slight inaccuracy in exercise 19

### ISSUE THREAD

**Issue by noc7c9** [ratfactor/ziglings#50]
Seems like a very minor issue but maybe worth fixing.

In exercise 19 the last comment states that:
std.math.pow(type, a, b) takes a numeric type and two numbers _**of that type**_
but that doesn't seem to be true, setting `my_number` to a `u8` works fine.

**Comment by ratfactor** [comment]
@noc7c9 That's an interesting point. You are correct about u8 being accepted.

The signature is `pub fn pow(comptime T: type, x: T, y: T) T`, so the parameters _are_ of that first parameter type.

But as you noted, the _arguments_ passed to the function may be other types as long as they can be safely coerced (basically, any smaller numeric type will work).  So I've added a clarifying parenthetical to the comment.

Thanks for the feedback!
