### ISSUE TITLE
Mark repo as template

### ISSUE THREAD

**Issue by SpexGuy** [ratfactor/ziglings#6]
In the repository settings, you can mark the repo as a template.  This allows users to create a copy of the repo without making a fork.  https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository

**Comment by ratfactor** [comment]
@SpexGuy Interesting! I didn't even know that was an option. Here we go:

![template](https://user-images.githubusercontent.com/1458409/107598022-96b69700-6bea-11eb-8ee7-1e59df9fe024.png)

Thanks for the suggestion!
