### ISSUE TITLE
CR/LF Issue

### ISSUE THREAD

**Issue by Androthi** [ratfactor/ziglings#60]
It should be noted somewhere in the readme that using an editor that produces CRLF at end of line will cause at least one of the lessons to fail, even though it generates the correct output.

**Comment by ratfactor** [comment]
@Androthi In fact, using such an editor will likely cause everything to fail.

https://github.com/ziglang/zig/issues/544

> The only hard rules are:
>  No Tabs
>  No Windows newlines
>  UTF-8 (or something that works as a subset of it, like ascii)

Thanks for the suggestion. You're right, based on the intended audience, this is something that should be in the Ziglings README.
