### ISSUE TITLE
Zigling #33 doesn't compile on newer versions.

### ISSUE THREAD

**Issue by danyildiabin** [ratfactor/ziglings#61]
**Code**
```
var n = numberMaybeFail(num);
if (n) |value| {
    std.debug.print("=4. ", .{});
} else |err| switch (err) {
    MyNumberError.TooBig => std.debug.print(">4. ", .{}),
}
```
**Result**
```
033_iferror.zig:32:17: error: unused capture
        if (n) |value| {
```

Easy avoidable by using that value in print(), but I think `#33` may need some changes to encourage proper use of that technique.

**Comment by ratfactor** [comment]
Thanks!  The compiler is starting to get strict, which is great. :-)

Actually, I think using the value in the print statement is a perfectly good fix (printing a verbatim '4' was the same thing anyway) and that's exactly what I've opted to do.

https://github.com/ratfactor/ziglings/commit/584993b7b8110bcfc5d8af543d889d671e78a484

**Comment by danyildiabin** [comment]
**Another one**
```
Compiling 051_values.zig...
051_values.zig:77:11: error: unused local constant
    const skull_farmer = Character{};
          ^
```
