### ISSUE TITLE
ZIG 0.9 Ambiguous reference error

### ISSUE THREAD

**Issue by danyildiabin** [ratfactor/ziglings#63]
**Problem**
In zigling 058 few print()'s defined so new ZIG won't compile.
Possible solution is to change first definition to `const print = @import("std")` and call standard print() using `std.debug.print()`.
Or just change method name in `TripItem` union to something else, like `printTrip()`,
so `const print = @import("std").debug.print;` still can be demonstrated.

**Code**
First print() was defined at line 31

```
const print = @import("std").debug.print;
```

Another print() was defined at line 183, so next references of print() becoming ambiguous?

```
fn print(self: TripItem) void {
        switch (self) {
            // Oops! The hermit forgot how to capture the union values
            // in a switch statement. Please capture both values as
            // 'p' so the print statements work!
            .place => |p| print("{s}", .{p.name}),
            .path => |p| print("--{}->", .{p.dist}),
        }
    }
```

**Compilation**
```
Compiling 051_values.zig...
051_values.zig:77:11: error: unused local constant
    const skull_farmer = Character{};
          ^
```

**Comment by ratfactor** [comment]
Yeah, this one took me by surprise. The official documentation uses the term "namespaced" for struct methods, which had lead me to believe that there wouldn't be a name collision!  I'm glad the compiler is catching this now.

I definitely got this one last night, but let me know if you spot any others!

Thanks! :heart:
