### ISSUE TITLE
Beautifying patches.

### ISSUE THREAD

**Issue by BiscayRobin** [ratfactor/ziglings#73]
I've done all your exercises. Those helped me so thank you.

I've read the patches to better grasp  the Zigly way of coding. It's, imo, the benefit of having access to them.

Some are not written in a Zigly way like 086_async3.patch.
Others have comments changing like 058_quiz7.patch.

Those little things could help beginners to write better code and not getting confused while reading patches.

**Comment by ratfactor** [comment]
Thanks for this! I agree completely. I did a cleanup phase on the patches a while back, but I'm not surprised they've drifted a bit.

**Comment by ratfactor** [comment]
Have not forgotten about this. There is guaranteed to be even more cleanup needed now. At one point I found going down a line of thinking that basically resulted in me writing a "better" diff/patch to maintain the current patches. I had to stop and tell myself, "There aren't that many. It's okay to maintain them manually." 😆

**Comment by ratfactor** [comment]
@BiscayRobin Patches cleaned! Thanks for creating this issue. 😄
