### ISSUE TITLE
Ex 003 "i" comment missing

### ISSUE THREAD

**Issue by hdcos** [ratfactor/ziglings#75]
```
//
// It seems we got a little carried away making everything "const u8"!
//
//     "const" values cannot change.
//     "u"     types are "unsigned" and cannot store negative values.
//     "8"     means the type is 8 bits in size.
```

we could add

```
//
// It seems we got a little carried away making everything "const u8"!
//
//     "const" values cannot change.
//     "u"     types are "unsigned" and cannot store negative values.
//=>=> "i"     types are "signed" and can store negative values.
//     "8"     means the type is 8 bits in size.
```

**Comment by aedrax** [comment]
I think the `i` is not relevant for this description since the comment is just describing the dissection of `const u8` and not providing an exhaustive list of types. Though another lesson showing more types may be a useful addition

**Comment by ratfactor** [comment]
@hdcos I'm going to go ahead and close this now, but please do comment/re-open/make a new one if you think there's a good place to add info about signed integers. Thanks!
