### ISSUE TITLE
Exercises for Allocators

### ISSUE THREAD

**Issue by s0LA1337** [ratfactor/ziglings#86]
Hello, first of all thanks for creating this Repo, it's been a great ressource to get used to zig so far.

However, now that i have essentially finished all the exercises, and i wanted to write a simple Brainfuck interpreter in Zig, i came across my first use of allocators, which (coming from C / C++) is a very major thing, which i believe has a great benefit to be also teached in Ziglings.

I am sort of in the middle of learning about allocators in zig and its usage so far, if i would have a better understanding of them yet, i would (or maybe will?) open a PR once i have learned about them in a more clear and detailed manner.

What is your opinion on that, as i have read that you do not want to teach about the standard library, yet i believe this is essentially a core part of Zig.

Cheers.

**Comment by ratfactor** [comment]
@s0LA1337 Excellent question! That's something I've been pondering as well:

* I agree that the way the Zig Standard Library handles allocators is unique and important to understand.
* On the other hand, they're not part of the core language.

Also, the Standard Library is still subject to a _lot_ of change in these pre-v1.0 days, as "Allocgate" demonstrates: https://ziglang.org/download/0.9.0/release-notes.html#Allocgate

So I'm not opposed to allocator exercises or other Standard Library material being included in Ziglings, but I _am_ cautious about needing to support it (or in a worst-case-scenario, having certain exercises cease to be relevant entirely!).

The other delay on my end is that in attempting to make the last **async** exercises, I realized that though I understood the mechanics, I didn't have a strong, fundamental, _working_ knowledge of using them. So I've been (very) slowly building that up by writing a toy HTTP server and toy HTTP client, both of which will use async as soon as I get that far 🤣.

But that's just what's delaying me.  As time has passed, I've become much more comfortable with the idea of playing an editorial role on submitted exercises. I certainly wouldn't want to prevent new high quality content from being added!  Maybe when it comes to standard library exercises, I'll just leave it to the community to provide?

**Comment by ratfactor** [comment]
Closing for now. Feel free to re-open!
