### ISSUE TITLE
Focus is good, but...

### ISSUE THREAD

**Issue by brandondrew** [ratfactor/ziglings#91]
> I've decide to limit Ziglings to the core language and not attempt coverage of the Standard Library. Perhaps you can change my mind?

I don't necessarily want to change your mind, as it's probably a good idea to keep this repo focused.  But what about starting a new repo for other people to contribute similar ziglings aimed at the standard library.  If everyone who went through your repo contributed one zigling for the standard library, you'd have an extensive collection in short order!

**Comment by ratfactor** [comment]
@brandondrew Yeah, I'd be totally down with hosting such a repo. I guess the hard part would be seeding it with some quality content to start with.  Do you feel like there would be an ideal order of learning, or should people just tackle stuff as their fancy strikes them?  For example, we should probably tackle conventions like allocator passing early on...or maybe it doesn't matter. Each exercise *could* just build on the previous - every contributor would need to make sure they explain any concepts not covered in a previous one.

The biggest challenge will be keeping it up-to-date. That could be entirely community-driven (and the repo could have a big disclaimer). I know that the Standard Library is expected to have lots of breaking changes between now and 1.0.

Thanks for the idea! And, by the way, if you want to create something like that yourself, feel free to copy the infrastructure (such as it is) from Ziglings. Also, I'd be delighted to link to it from Ziglings.

**Comment by brandondrew** [comment]
Thanks! I would also love to host it but I don't think I would be the ideal person, given that I just discovered Zig a couple days ago 😄.

**Comment by ratfactor** [comment]
@brandondrew Nonsense, what better way to learn. 🤣

**Comment by brandondrew** [comment]
> @brandondrew Nonsense, what better way to learn. 🤣

hahahha, I guess you have a good point! 😄

**Comment by s0LA1337** [comment]
> Thanks for the idea! And, by the way, if you want to create something like that yourself, feel free to copy the infrastructure (such as it is) from Ziglings. Also, I'd be delighted to link to it from Ziglings.

If someone would be down, they could contact me, i definetly want something to work a bit on, and help (not alone, since i am also not 100% proficient with Zig just yet) would be an amazing learning process as well, i suppose.
I would also be interested in this, given that I also have proposed for the Allocator addition, and i believe this may actually have a better fit in a standard library learning repo

**Comment by bleuge** [comment]
Hi, just discovered this repo, only 1 day with zig ;D
But I want to note something that I've learn when I try to learn new languages.
This is my case, probably you have other needs. 
The basic things I need to look for in a library, are things as
- strings stuff 
- inttostr, and all the rest...
- some json/xml serializing/loading data
- maybe some easy db stuff , as sqlite, useful for logs, admins things, etc 
- (if supported right now :D  I don't know) 
- how to open a raw/text file, load data, write back to disk
- other file related things, as directories, file searching
- I don't usually code things that need to do network things, but as I said, this is are some cases. 

Maybe something like this could be an approach to sort/organize the material. Choosing some general/basic user-cases and start there. 
It could be great If I can learn enough about zig so I can contribute to that repo. 
Regards.

**Comment by ratfactor** [comment]
I'm going to go ahead and close this for now. Feel free to re-open if anybody has anything new to add!

**Comment by hippietrail** [comment]
Would it be possible to start off with just feature requests? I don't know if it's kosher to have a repo on GitHub with no code but having a tracker to work out what things would need to go in first would be helpful.

I can think of two directions for such suggestions:

1. Things you always need to know how to do in a new language.
2. Standard library features that exist that should have questions, especially ones you found tricky to learn.

Maybe 3. could be seeing what Rustlings does for some inspiration.

**Comment by ratfactor** [comment]
@hippietrail It is _definitely_ okay to use a GitHub repo to organize a not-yet-extant codebase!  And your numbered topics sound like a great starting point. I've even got a name: "Beyond Ziglings". :-)

If you make one, I'll have the README point to it!
