### ISSUE TITLE
Misleading description of ++ operator

### ISSUE THREAD

**Issue by nekodjin** [ratfactor/ziglings#93]
Exercise No. 005 (arrays2) contains the following description of the `++` operator:
> You can use `++` to concatenate two arrays:
> ```zig
> const a = [_]u8{ 1, 2 };
> const b = [_]u8{ 3, 4 };
> const c = a ++ b ++ [_]u8{ 5 }; // equals 1 2 3 4 5
> ```
This is slightly misleading, as it neglects to mention that (for now?) the `++` operator [can only be used on arrays whose values are known at compiletime][source].

I would submit a PR to fix this but I'm honestly not quite sure how it should be amended, since the concept of comptime seems to be introduced somewhere in the 70's.

[source]: https://ziglang.org/documentation/0.9.1/#:~:text=Array%20concatenation.-,Only%20available%20when%20a%20and%20b%20are%20compile%2Dtime%20known.,-const%20mem%20%3D%20%40import

**Comment by nekodjin** [comment]
This also applies to Exercise No. 005's description of the `**` operator.

**Comment by ratfactor** [comment]
@nekodjin Hmmm. That's a very good point. Seems like the trick is succinctly describing what's being done without using the term "comptime".

**Comment by eritain** [comment]
Most good curricula are spirals, and this kind of thing is why. 

You don't have to teach the whole concept before its time, you just have to stick a little flag in it. That way, when we learners reach it we won't have to completely reconceptualize these operators. And if someone gets adventurous before then and runs into comptime issues, they will have some idea what info to look for.

"Note: Values and expressions have a special status in Zig if they can be known when the program is compiled. `++` and `**` only work on these so-called 'comptime' values. More about that later."

**Comment by ratfactor** [comment]
@eritain Very true. And thanks for the suggested wording!

@nekodjin Thanks for bringing this up!

I ended up adding:

```
// Note that both '++' and '**' only operate on arrays while your
// program is _being compiled_. This special time is known in Zig
// parlance as "comptime" and we'll learn plenty more about that
// later.
```
