### ISSUE TITLE
`zig build` fails with zig 0.10.0-dev.1888

### ISSUE THREAD

**Issue by mwcz** [ratfactor/ziglings#96]
I came to check out ziglings, got the nightly build from 2022-04-20, and saw the following error.

```
$ zig version
0.10.0-dev.1888+e3cbea934

$ zig build
/home/user/.local/lib/std/compress/deflate.zig:25:56: error: unable to override alignment of packed struct fields
    const LUTEntry = packed struct { symbol: u16 align(4), len: u16 };
                                                       ^
/home/user/.local/lib/std/builtin.zig:252:19: error: expected type expression, found 'anytype'
        sentinel: anytype,
                  ^
```

**Comment by ratfactor** [comment]
@mwcz Hmmm, I just tried with the nightly 0.10.0 build and was not able to replicate this problem:

```
$ zig version
0.10.0-dev.1927+cf20b97b7

$ zig build

         _       _ _
     ___(_) __ _| (_)_ __   __ _ ___
    |_  | |/ _' | | | '_ \ / _' / __|
     / /| | (_| | | | | | | (_| \__ \
    /___|_|\__, |_|_|_| |_|\__, |___/
           |___/           |___/

Compiling 001_hello.zig...
```

Maybe your Zig library was somehow not in sync with the executable or something like that. Could you try a fresh build and try again?

Thanks!

**Comment by mwcz** [comment]
Ah, I think you're exactly right. I'm pretty sure I copied in the zig binary but not the library so that's almost certainly the problem.  I'll give it another shot soon.

**Comment by mwcz** [comment]
Yep, it works now.  But now there are all these errors in the exercise files. :rofl: 

Thanks for the help, and sorry for the false alarm.
